import { check, sleep } from "k6";
import { SharedArray } from "k6/data";
import exec from "k6/execution";
import http from "k6/http";

// 1. Load the 100 users generated by your Laravel seeder
const users = new SharedArray("seeded_users", function () {
    return JSON.parse(open("./users.json"));
});

// Configure the stress test payload
export const options = {
    scenarios: {
        realistic_shopping: {
            executor: "per-vu-iterations",
            vus: 100, // 100 Concurrent Users
            iterations: 3, // Each user loops this 100 times
            maxDuration: "10m",
        },
    },
};

export default function () {
    // If you use Laravel's default API routing, this should be /api
    // Adjust if your routes don't use the /api prefix
    const baseUrl = "http://localhost:8001/api";
    const user = users[exec.vu.idInTest - 1];

    const jsonHeaders = {
        Accept: "application/json",
        "Content-Type": "application/json",
    };

    // --- 1. LOGIN ---
    const loginRes = http.post(
        `${baseUrl}/auth/login`,
        JSON.stringify({
            email: user.email,
            password: user.password,
        }),
        { headers: jsonHeaders },
    );

    // Validate login success before proceeding
    const loginSuccessful = check(loginRes, {
        "Logged in successfully": (r) => r.status === 200,
    });

    if (!loginSuccessful) {
        console.log(
            `[LOGIN FAILED] Status: ${loginRes.status} | Body: ${loginRes.body}`,
        );
        // If login fails, wait and exit this iteration early so we don't crash
        sleep(1);
        return;
    }

    // Extract the token based on your Postman schema: res.data.access_token
    const token = loginRes.json("data.access_token");

    // Set up headers for all subsequent authenticated requests
    const authHeaders = {
        Accept: "application/json",
        "Content-Type": "application/json",
        Authorization: `Bearer ${token}`,
    };

    // --- 2. FETCH PRODUCTS ---
    const productsRes = http.get(`${baseUrl}/products`, {
        headers: authHeaders,
    });

    check(productsRes, {
        "Fetched products": (r) => r.status === 200,
    });

    // Extract the products array based on your Postman schema: res.data
    const products = productsRes.json("data");

    if (!products || products.length === 0) {
        return; // Failsafe if DB is empty
    }

    // --- 3. CHOOSE 1 OR 2 RANDOM PRODUCTS ---
    // Decide randomly whether to buy 1 or 2 items
    const numItemsToBuy = Math.random() > 0.5 ? 2 : 1;
    const selectedProducts = [];

    for (let i = 0; i < numItemsToBuy; i++) {
        // Pick a random product
        const randomIndex = Math.floor(Math.random() * products.length);
        selectedProducts.push(products[randomIndex]);

        // Remove it from the pool so we don't pick the exact same product twice
        // (unless you want to test increasing quantity, but separate cart items is better for lock testing)
        products.splice(randomIndex, 1);
    }

    // --- 4. ADD TO CART ---
    for (const product of selectedProducts) {
        const cartRes = http.post(
            `${baseUrl}/cart`,
            JSON.stringify({
                product_id: product.id,
                quantity: 1, // Adding 1 of each selected product
            }),
            { headers: authHeaders },
        );

        check(cartRes, {
            "Added to cart (201)": (r) => r.status === 201,
        });

        // Small delay between adding multiple items
        // sleep(0.2);
    }

    // --- 5. CHECKOUT (PLACE ORDER) ---
    // Postman shows no body required for orders.store
    const orderRes = http.post(`${baseUrl}/orders`, null, {
        headers: authHeaders,
    });

    // Based on Postman, success is 201 Created.
    // If your locks reject overselling, expect a 4xx error (e.g., 422 or 400).
    const orderSuccessful = check(orderRes, {
        "Order placed (201)": (r) => r.status === 201,
    });

    if (!orderSuccessful) {
        const failedDueToStock = check(orderRes, {
            "Order failed due to stock (4xx)": (r) =>
                r.status >= 400 && r.status < 500,
        });

        if (!failedDueToStock) {
            console.log(
                `[ORDER FAILED] Unexpected status: ${orderRes.status} | Body: ${orderRes.body}`,
            );
        }
        // console.log(
        //     `[ORDER FAILED] Status: ${orderRes.status} | Body: ${orderRes.body}`,
        // );
    }
}
